#cloud-config
# Add groups to the system
# Adds the ubuntu group with members 'root' and 'sys'
# and the empty group hashicorp.
groups:
  - ubuntu: [root,sys]
  - hashicorp

# Add users to the system. Users are added after groups are added.
users:
  - default
  - name: terraform
    gecos: terraform
    shell: /bin/bash
    primary_group: hashicorp
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    ssh_import_id:
    lock_passwd: false
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC6fwJsF5WFlgdKWZv5FpcowHY2DvTyl3ALqKsIQ+bSi3q3nisM6h+2mdbrO+P5zZWo6U/3/RHWn2EXXwfdfUq+U8GVjRzt1DeL5fnS9c8Amsf0bYpIylE8Cy4aocXhLuetFK+bIHgkWVKgm6/NM9MU2ap3SLZguFJlC8psS/JGJgfUbZeuzFq8McIFBaMZquzY2tew3oP4GIlcoUX/djdK1JnOkC3reOTxGTlOKscK1yg1hOYxYkqWS5tn/5mDD1vNT6upmLOjulfPgc6P3ae4NzydsN+VXrjUqkoLCUsS0GE2GZoHqPLpvZz7aU3JwQRbY464OCNHNd2lcdPZYJ6dxMSeyFMTT0IxxuBjyHjo7vnZMy2WSBW1SD4RjWJoiPYsXQA817vN6J0FnrkFWBr02KkByzhESJ+CRK0hWCzS8L/VIOzt+Qz0AcKL55h6arKhPLo5Fshe6ni3aPeku9pQB1g52iJGOMFjPPRD5BjAKZXKEPVO44C0K/GA4u7zsRE= andrii@hashicorp.com

# Downloads the golang package
packages:
  - golang-go

# Setsthe GOPATH & downloads the demo payload
runcmd:
  - sudo su terraform
  - sudo mkdir ~/go
  - export GOPATH=$HOME/go
  - sudo go get github.com/hashicorp/learn-go-webapp-demo
